package com.covoro.validationservice.master;

public enum ItemClassification {

    PRODUCT_VERSION_NUMBER("AA", "Product version number - Number assigned by manufacturer or seller to identify the release of a product."),
    ASSEMBLY("AB", "Assembly - The item number is that of an assembly."),
    HIBC("AC", "HIBC (Health Industry Bar Code) - Article identifier used within health sector to indicate data used conforms to HIBC."),
    COLD_ROLL_NUMBER("AD", "Cold roll number - Number assigned to a cold roll."),
    HOT_ROLL_NUMBER("AE", "Hot roll number - Number assigned to a hot roll."),
    SLAB_NUMBER("AF", "Slab number - Number assigned to a slab, which is produced in a particular production step."),
    SOFTWARE_REVISION_NUMBER("AG", "Software revision number - A number assigned to indicate a revision of software."),
    UPC_CONSUMER_PACKAGE_CODE_11("AH", "UPC Consumer package code (1-5-5) - 11-digit code without check digit."),
    UPC_CONSUMER_PACKAGE_CODE_12("AI", "UPC Consumer package code (1-5-5-1) - 12-digit code including check digit."),
    SAMPLE_NUMBER("AJ", "Sample number - Number assigned to a sample."),
    PACK_NUMBER("AK", "Pack number - Number assigned to a pack containing stacked items."),
    UPC_SHIPPING_CONTAINER_CODE_13("AL", "UPC Shipping container code (1-2-5-5) - 13-digit code including packaging indicator."),
    UPC_EAN_SHIPPING_CONTAINER_CODE("AM", "UPC/EAN Shipping container code (1-2-5-5-1)."),
    UPC_SUFFIX("AN", "UPC suffix - Defines packing variations."),
    STATE_LABEL_CODE("AO", "State label code - Specifies the codification of the state's labelling requirements."),
    HEAT_NUMBER("AP", "Heat number - Number assigned to a steel heat/iron charge."),
    COUPON_NUMBER("AQ", "Coupon number - Identifying a coupon."),
    RESOURCE_NUMBER("AR", "Resource number - To identify a resource."),
    WORK_TASK_NUMBER("AS", "Work task number - To identify a work task."),
    PRICE_LOOKUP("AT", "Price look up number - Identification number for quick price retrieval."),
    NATO_STOCK_NUMBER("AU", "NSN - NATO Stock Number for supply items."),
    REFINED_PRODUCT_CODE("AV", "Refined product code - Specifies refinement designation."),
    EXHIBIT("AW", "Exhibit - Product identified by an exhibit."),
    END_ITEM("AX", "End item - Number specifying an end item."),
    FEDERAL_SUPPLY_CLASSIFICATION("AY", "Federal supply classification."),
    ENGINEERING_DATA_LIST("AZ", "Engineering data list."),
    MILESTONE_EVENT_NUMBER("BA", "Milestone event number."),
    LOT_NUMBER("BB", "Lot number."),
    NATIONAL_DRUG_CODE_442("BC", "National drug code 4-4-2 format."),
    NATIONAL_DRUG_CODE_532("BD", "National drug code 5-3-2 format."),
    NATIONAL_DRUG_CODE_541("BE", "National drug code 5-4-1 format."),
    NATIONAL_DRUG_CODE_542("BF", "National drug code 5-4-2 format."),
    NATIONAL_DRUG_CODE("BG", "National drug classification."),
    PART_NUMBER("BH", "Part number."),
    LOCAL_STOCK_NUMBER("BI", "Local Stock Number (LSN)."),
    NEXT_HIGHER_ASSEMBLY("BJ", "Next higher assembly number."),
    DATA_CATEGORY("BK", "Data category."),
    CONTROL_NUMBER("BL", "Control number."),
    SPECIAL_MATERIAL_ID("BM", "Special material identification code."),
    LOCAL_CONTROL_NUMBER("BN", "Locally assigned control number."),
    BUYER_COLOUR("BO", "Buyer’s colour."),
    BUYER_PART_NUMBER("BP", "Buyer’s part number."),
    VARIABLE_MEASURE_PRODUCT("BQ", "Variable measure product code."),
    FINANCIAL_PHASE("BR", "Financial phase."),
    CONTRACT_BREAKDOWN("BS", "Contract breakdown."),
    TECHNICAL_PHASE("BT", "Technical phase."),
    DYE_LOT_NUMBER("BU", "Dye lot number."),
    DAILY_STATEMENT("BV", "Daily statement of activities."),
    PERIODICAL_STATEMENT("BW", "Periodical statement of activities."),
    CALENDAR_WEEK_STATEMENT("BX", "Calendar week statement."),
    CALENDAR_MONTH_STATEMENT("BY", "Calendar month statement."),
    ORIGINAL_EQUIPMENT_NUMBER("BZ", "Original equipment number."),
    INDUSTRY_COMMODITY_CODE("CC", "Industry commodity code."),
    COMMODITY_GROUPING("CG", "Commodity grouping."),
    COLOUR_NUMBER("CL", "Colour number."),
    CONTRACT_NUMBER("CR", "Contract number."),
    CUSTOMS_ARTICLE_NUMBER("CV", "Customs article number."),
    DRAWING_REVISION("DR", "Drawing revision number."),
    DRAWING("DW", "Drawing reference."),
    ENGINEERING_CHANGE_LEVEL("EC", "Engineering change level."),
    MATERIAL_CODE("EF", "Material code."),
    EMDN("EMD", "European Medical Device Nomenclature."),
    EAN("EN", "International Article Number."),
    FISH_SPECIES("FS", "Fish species."),
    BUYER_INTERNAL_PRODUCT_GROUP("GB", "Buyer’s internal product group code."),
    GLOBAL_MODEL_NUMBER("GMN", "Global model number."),
    NATIONAL_PRODUCT_GROUP_CODE("GN", "National product group code."),
    GENERAL_SPECIFICATION("GS", "General specification number."),
    HARMONISED_SYSTEM("HS", "Harmonised system."),
    ISBN("IB", "International Standard Book Number."),
    BUYER_ITEM_NUMBER("IN", "Buyer’s item number."),
    ISSN("IS", "International Standard Serial Number."),
    BUYER_STYLE_NUMBER("IT", "Buyer’s style number."),
    BUYER_SIZE_CODE("IZ", "Buyer’s size code."),
    MACHINE_NUMBER("MA", "Machine number."),
    MANUFACTURER_ARTICLE_NUMBER("MF", "Manufacturer’s article number."),
    MODEL_NUMBER("MN", "Model number."),
    PRODUCT_SERVICE_ID("MP", "Product/service identification number."),
    BATCH_NUMBER("NB", "Batch number."),
    CUSTOMER_ORDER_NUMBER("ON", "Customer order number."),
    PART_NUMBER_DESCRIPTION("PD", "Part number description."),
    PURCHASE_ORDER_LINE_NUMBER("PL", "Purchaser’s order line number."),
    PURCHASE_ORDER_NUMBER("PO", "Purchase order number."),
    PROMOTIONAL_VARIANT_NUMBER("PV", "Promotional variant number."),
    BUYER_SIZE_QUALIFIER("QS", "Buyer’s qualifier for size."),
    RETURNABLE_CONTAINER_NUMBER("RC", "Returnable container number."),
    RELEASE_NUMBER("RN", "Release number."),
    RUN_NUMBER("RU", "Run number."),
    RECORD_KEEPING_MODEL_YEAR("RY", "Record keeping of model year."),
    SUPPLIER_ARTICLE_NUMBER("SA", "Supplier’s article number."),
    STANDARD_GROUP_PRODUCTS("SG", "Standard group of products (mixed assortment)."),
    SKU("SK", "Stock keeping unit."),
    SERIAL_NUMBER("SN", "Serial number."),
    RSK("SRS", "Plumbing and heating."),
    IFLS_5_DIGIT("SRT", "IFLS (Institut Francais du Libre Service) 5 digit product classification code."),
    IFLS_9_DIGIT("SRU", "IFLS (Institut Francais du Libre Service) 9 digit product classification code."),
    GS1_GTIN("SRV", "GS1 Global Trade Item Number."),
    EDIS("SRW", "EDIS (Energy Data Identification System)."),
    SLAUGHTER_NUMBER("SRX", "Slaughter number."),
    OFFICIAL_ANIMAL_NUMBER("SRY", "Official animal number."),
    HARMONIZED_TARIFF("SRZ", "Harmonized tariff schedule."),
    SUPPLIER_SUPPLIER_ARTICLE("SS", "Supplier's supplier article number."),
    DOT_46_LEVEL("SSA", "46 Level DOT Code."),
    AIRLINE_TARIFF_6D("SSB", "Airline Tariff 6D."),
    TITLE_49_CFR("SSC", "Title 49 Code of Federal Regulations."),
    ICAO_CODE("SSD", "International Civil Aviation Administration code."),
    HAZMAT_ID_DOT("SSE", "Hazardous Materials ID DOT."),
    ENDORSEMENT("SSF", "Endorsement."),
    AIR_FORCE_REG("SSG", "Air Force Regulation 71-4."),
    BREED("SSH", "Breed."),
    CAS("SSI", "Chemical Abstract Service (CAS) registry number."),
    ENGINE_MODEL("SSJ", "Engine model designation."),
    IMPS("SSK", "Institutional Meat Purchase Specifications (IMPS) Number."),
    PLU("SSL", "Price Look-Up code (PLU)."),
    IMO_CODE("SSM", "International Maritime Organization (IMO) Code."),
    BOE_600A("SSN", "Bureau of Explosives 600-A (rail)."),
    UN_DANGEROUS_GOODS("SSO", "United Nations Dangerous Goods List."),
    ICBN("SSP", "International Code of Botanical Nomenclature (ICBN)."),
    ICZN("SSQ", "International Code of Zoological Nomenclature (ICZN)."),
    ICNCP("SSR", "International Code of Nomenclature for Cultivated Plants (ICNCP)."),
    DISTRIBUTOR_ARTICLE("SSS", "Distributor’s article identifier."),
    ENVA("SST", "Norwegian Classification system ENVA."),
    SUPPLIER_CLASSIFICATION("SSU", "Supplier assigned classification."),
    AMECE("SSV", "Mexican classification system AMECE."),
    CCG("SSW", "German classification system CCG."),
    EANFIN("SSX", "Finnish classification system EANFIN."),
    ICC("SSY", "Canadian classification system ICC."),
    IFLS5("SSZ", "French classification system IFLS5."),
    STYLE_NUMBER("ST", "Style number."),
    CBL("STA", "Dutch classification system CBL."),
    JICFS("STB", "Japanese classification system JICFS."),
    EU_DAIRY_SUBSIDY("STC", "European Union dairy subsidy eligibility classification."),
    GS1_SPAIN("STD", "GS1 Spain classification system."),
    GS1_POLAND("STE", "GS1 Poland classification system."),
    RUSSIAN_STANDARD("STF", "Federal Agency on Technical Regulating and Metrology of the Russian Federation."),
    ECR_AUSTRIA("STG", "Efficient Consumer Response (ECR) Austria classification system."),
    GS1_ITALY("STH", "GS1 Italy classification system."),
    CPV("STI", "CPV (Common Procurement Vocabulary)."),
    IFDA("STJ", "IFDA (International Foodservice Distributors Association)."),
    AHFS("STK", "AHFS pharmacologic-therapeutic classification."),
    ATC("STL", "ATC (Anatomical Therapeutic Chemical) classification system."),
    CLADIMED("STM", "CLADIMED classification system."),
    CMDR("STN", "CMDR (Canadian Medical Device Regulations) classification system."),
    CNDM("STO", "CNDM (Classificazione Nazionale dei Dispositivi Medici)."),
    UK_DMD("STP", "UK DM&D standard coding scheme."),
    ECLASS("STQ", "eCl@ss classification."),
    EDMA("STR", "EDMA (European Diagnostic Manufacturers Association) classification."),
    EGAR("STS", "EGAR classification."),
    GMDN("STT", "GMDN (Global Medical Devices Nomenclature)."),
    GPI("STU", "GPI (Generic Product Identifier)."),
    HCPCS("STV", "HCPCS classification."),
    ICPS("STW", "ICPS (International Classification for Patient Safety)."),
    MEDDRA("STX", "MedDRA (Medical Dictionary for Regulatory Activities)."),
    MEDICAL_COLUMBUS("STY", "Medical Columbus."),
    NAPCS("STZ", "NAPCS (North American Product Classification System)."),
    NHS_ECLASS("SUA", "NHS (National Health Services) eClass."),
    FDA_PRODUCT_CODE("SUB", "US FDA Product Code Classification Database."),
    SNOMED_CT("SUC", "SNOMED CT."),
    UMDNS("SUD", "UMDNS."),
    GS1_RETURNABLE("SUE", "GS1 Global Returnable Asset Identifier, non-serialised."),
    IMEI("SUF", "IMEI."),
    EMSA("SUG", "Waste Type (EMSA)."),
    SHIPS_STORE("SUH", "Ship's store classification type."),
    FIRE_CODE("SUI", "Emergency fire code."),
    SPILLAGE_CODE("SUJ", "Emergency spillage code."),
    IMDG_PACKING("SUK", "IMDG packing group."),
    MARPOL("SUL", "MARPOL Code IBC."),
    IMDG_SUBSIDIARY("SUM", "IMDG subsidiary risk class."),
    TRANSPORT_GROUP("TG", "Transport group number."),
    TSN("TSN", "Taxonomic Serial Number."),
    IMDG_MAIN_HAZARD("TSO", "IMDG main hazard class."),
    EU_COMBINED_NOMENCLATURE("TSP", "EU Combined Nomenclature."),
    THERAPEUTIC_CLASSIFICATION("TSQ", "Therapeutic classification number."),
    EWC("TSR", "European Waste Catalogue."),
    PRICE_GROUPING("TSS", "Price grouping code."),
    UNSPSC("TST", "UNSPSC."),
    EU_ROHS("TSU", "EU RoHS Directive."),
    ULTIMATE_CUSTOMER_ARTICLE("UA", "Ultimate customer's article number."),
    UPC("UP", "UPC (Universal product code)."),
    VENDOR_ITEM("VN", "Vendor item number."),
    VENDOR_PART("VP", "Vendor's (seller's) part number."),
    VENDOR_SUPPLEMENTAL("VS", "Vendor's supplemental item number."),
    VENDOR_SPEC("VX", "Vendor specification number."),
    MUTUALLY_DEFINED("ZZZ", "Mutually defined - Item type identification mutually agreed between parties.");

    final String code;
    final String description;


    ItemClassification(String code, String description) {
        this.description = description;
        this.code = code;
    }

}
